---
modules:
    show:
        - welcome
        - locale
        - keyboard
        - partition
        - users
        - summary
        - finished
    prepare:
        - welcome
        - locale
        - keyboard
        - partition
        - mount
        - unpackfs
        - machineid
        - fstab
        - localecfg
        - users
        - displaymanager
        - initramfscfg
        - initramfs
        - grubcfg
        - bootloader
        - luksopenswaphookcfg
        - hwclock
        - services-systemd
        - removeuser
        - umount

branding: ubuntu

welcome-installer: false

welcome-mode: false

prompt-install: false

dont-chroot: false

show-notification: false

donate-url: ""

release-notes-url: ""
