[options]
HoldPkg     = pacman glibc
Architecture = auto
SigLevel    = Never

[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[multilib]
Include = /etc/pacman.d/mirrorlist
